import { deviceId } from "./device";

export type Movie = {
  id: string;
  slug: string;
  title: string;
  runtimeMinutes: number;
  certification: string;
  genres: string[];
  releaseDate: string;
  posterUrl: string | null;
};

export type Cinema = {
  id: string;
  slug: string;
  name: string;
  city: string;
  screenCount: number;
};

export type Show = {
  id: string;
  /// Mongo `_id` as a hex string. Present on every show so one can be passed
  /// around without the film it belongs to going missing.
  movieId: string;
  startsAt: string;
  endsAt: string;
  screen: string;
  format: string;
  /// Integer minor units. Converted to a decimal only by the price formatter.
  priceCents: number;
};

export type MovieShowtimes = { movie: Movie; shows: Show[] };

export type Showtimes = {
  cinema: Omit<Cinema, "screenCount">;
  date: string;
  dates: string[];
  movies: MovieShowtimes[];
};

export type SeatStatus = "AVAILABLE" | "HELD" | "BOOKED";

export type SeatMapSeat = {
  id: string;
  seatId: string;
  label: string;
  gridRow: number;
  gridCol: number;
  kind: "STANDARD" | "PREMIUM" | "ACCESSIBLE";
  status: SeatStatus;
  mine: boolean;
  priceCents: number;
};

export type SeatMap = {
  show: {
    id: string;
    startsAt: string;
    format: string;
    screen: string;
    cinema: string;
    movieTitle: string;
  };
  rows: number;
  cols: number;
  seats: SeatMapSeat[];
};

export type Reservation = {
  id: string;
  showId: string;
  status: "ACTIVE" | "CONFIRMED" | "EXPIRED" | "CANCELLED";
  expiresAt: string | null;
  secondsRemaining: number;
  show: { startsAt: string; format: string; screen: string; cinema: string };
  seats: { label: string; priceCents: number }[];
  totalCents: number;
};

/// Carries the API's own 4xx message through as the Error message, so pages can
/// show "Only 0 of 2 seats were still available" rather than a bare status.
/// `status` is attached so callers can branch on 409 vs 410 without parsing text.
export class ApiError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly code: string | null
  ) {
    super(message);
    this.name = "ApiError";
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`/api${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      "X-Device-Id": deviceId(),
      ...init?.headers,
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new ApiError(
      typeof body?.message === "string" ? body.message : `${path} failed with ${res.status}`,
      res.status,
      typeof body?.error === "string" ? body.error : null
    );
  }

  return res.json() as Promise<T>;
}

export const fetchMovies = () => request<Movie[]>("/movies");
export const fetchCinemas = () => request<Cinema[]>("/cinemas");

export function fetchShowtimes(cinemaSlug: string, date?: string) {
  const query = date ? `?date=${encodeURIComponent(date)}` : "";
  return request<Showtimes>(`/cinemas/${encodeURIComponent(cinemaSlug)}/showtimes${query}`);
}

export const fetchSeatMap = (showId: string) =>
  request<SeatMap>(`/shows/${encodeURIComponent(showId)}/seats`);

export const fetchReservation = (holdId: string) =>
  request<Reservation>(`/reservations/${encodeURIComponent(holdId)}`);

/// `idempotencyKey` is generated by the caller and kept stable across retries of
/// the *same* user intent, so a double-tap or a flaky network cannot produce two
/// holds. A genuinely new attempt must use a new key.
export function createReservation(showId: string, seatIds: string[], idempotencyKey: string) {
  return request<Reservation>("/reservations", {
    method: "POST",
    body: JSON.stringify({ showId, seatIds, idempotencyKey }),
  });
}

export const confirmReservation = (holdId: string) =>
  request<Reservation>(`/reservations/${encodeURIComponent(holdId)}/confirm`, { method: "POST" });
